name: PhqzeCapes
author: Phqzing
version: 0.0.1
api: 4.0.0
main: Phqzing\PhqzeCapes\Loader

commands:
  capes:
    description: "main command for Phqze Capes."
    permission: capes.command.use

permissions:
  capes.command.use:
    default: true
  capes.remove.use:
    default: op
