name: PhqzeCapes
author: Phqzing
version: 0.0.1
api: 4.0.0
main: Phqzing\PhqzeCapes\Loader

commands:
  capes:
    description: "main command for Phqze Capes."
    permission: phqzecapes.command.use

permissions:
  phqzecapes.command.use:
    default: true
  phqzecapes.remove.use:
    default: op
